"""Derive every computed template value from the merged config.

This is the only place values are computed; templates just loop and branch.
"""

from __future__ import annotations

import os
import posixpath
from pathlib import Path

from . import variants
from .config import Config, deep_merge

SERVICE = "ros2-dev"


def build(cfg: Config) -> dict:
    d = cfg.data
    name, distro = d["project"]["name"], d["ros"]["distro"]
    root = cfg.output_root
    dirs = {key: d["output"][f"{key}_dir"] for key in ("docker", "devcontainer", "vscode")}
    docker_dir = root / dirs["docker"]
    workspace_dir = (root / d["workspace"]["host_path"]).resolve()
    container_root = d["workspace"]["container_path"]
    ros_ws = posixpath.normpath(posixpath.join(container_root, d["workspace"]["ros_ws_subdir"]))
    install_dir = f"/opt/{name}"
    enabled_variants = variants.enabled(d)
    ide_scripts = d["editor"]["enabled"] or d["ide"]["pyright_config"]
    post_create = d["editor"]["post_create_command"]
    if ide_scripts:
        post_create += f" && python3 {install_dir}/scripts/generate_ide_config.py"

    def in_container(host_path: Path) -> str | None:
        """Where a host path under the workspace mount appears inside the container."""
        rel = os.path.relpath(host_path, workspace_dir)
        return None if rel.startswith("..") else posixpath.normpath(posixpath.join(container_root, rel))

    return {
        **d,
        "header": f"Generated by ros2-container from {cfg.config_name}. Edit that file and re-run generate.sh instead of editing this one.",
        "dirs": dirs,
        "service": SERVICE,
        "image": f"{name}-ros2-{distro}:dev",
        "base_image": d["ros"]["base_image"].format(distro=distro),
        "install_dir": install_dir,
        "ros_ws": ros_ws,
        "workspace_mount": _rel(workspace_dir, docker_dir),
        "rmw_package": _ros_package(distro, d["rmw"]["implementation"]),
        "use_cyclonedds": d["rmw"]["implementation"] == "rmw_cyclonedds_cpp",
        "ros_apt_groups": {g: [_ros_package(distro, p) for p in pkgs] for g, pkgs in d["dependencies"]["ros"].items()},
        "rosdep_rules": _read_optional(cfg.config_dir, d["rosdep"]["rules_file"]),
        "variants": enabled_variants,
        "overlays": sorted({o for v in enabled_variants for o in v.overlays}),
        "ide_scripts": ide_scripts,
        "ide_files": {
            "settings": in_container(root / dirs["vscode"] / "settings.json") if d["editor"]["enabled"] else None,
            "pyright": in_container(root / "pyrightconfig.json") if d["ide"]["pyright_config"] else None,
        },
        "devcontainers": _devcontainers(d, enabled_variants, root / dirs["devcontainer"], docker_dir, post_create),
        "vscode_settings": _vscode_settings(d, ros_ws),
        "pyright_config": {"extraPaths": [], "exclude": ["**/build", "**/install", "**/log"]},
    }


def _devcontainers(
    d: dict, enabled_variants: list[variants.Variant], devcontainer_dir: Path, docker_dir: Path, post_create: str
) -> list[dict]:
    """One devcontainer.json per (variant, editor); cursor configs get a `-cursor` suffix."""
    if not d["editor"]["enabled"]:
        return []
    out = []
    for editor in d["editor"]["editors"]:
        extensions = d["editor"]["extensions"]["common"] + d["editor"]["extensions"][editor]
        for v in enabled_variants:
            folder = v.name if editor == "vscode" else f"{v.name}-cursor"
            config = {
                "name": f"{d['project']['display_name']} ({v.label})",
                "dockerComposeFile": [_rel(docker_dir / f, devcontainer_dir / folder) for f in v.compose_files],
                "service": SERVICE,
                "workspaceFolder": d["workspace"]["container_path"],
                "postCreateCommand": post_create,
                "customizations": {
                    "vscode": {
                        "extensions": extensions,
                        "settings": {
                            "terminal.integrated.defaultProfile.linux": "bash",
                            "terminal.integrated.profiles.linux": {"bash": {"path": "bash", "args": ["-l"]}},
                        },
                    }
                },
                "remoteUser": "root",
            }
            if "linux" in v.overlays:  # let the container draw on the host's X server
                config["initializeCommand"] = "command -v xhost >/dev/null && xhost +local: >/dev/null || true"
            out.append({"folder": folder, "config": config})
    return out


def _vscode_settings(d: dict, ros_ws: str) -> dict:
    # extraPaths start empty; generate_ide_config.py fills them in the container after each build.
    base = {
        "python.analysis.extraPaths": [],
        "python.autoComplete.extraPaths": [],
        "C_Cpp.default.compileCommands": f"{ros_ws}/compile_commands.json",
        "clangd.arguments": [f"--compile-commands-dir={ros_ws}"],
    }
    return deep_merge(base, d["editor"]["settings"])


def _ros_package(distro: str, name: str) -> str:
    return name if name.startswith("ros-") else f"ros-{distro}-{name.replace('_', '-')}"


def _rel(target: Path, start: Path) -> str:
    """Relative path that compose treats as a path (not a named volume)."""
    rel = Path(os.path.relpath(target, start)).as_posix()
    return rel if rel.startswith(".") else f"./{rel}"


def _read_optional(base: Path, path: str | None) -> str | None:
    return (base / path).read_text() if path else None
