"""Derive every computed template value from the merged config.

This is the only place values are computed; templates just loop and branch.
"""

from __future__ import annotations

import os
import posixpath
from pathlib import Path

from . import variants
from .config import Config, deep_merge

SERVICE = "ros2-dev"


def build(cfg: Config) -> dict:
    d = cfg.data
    name, distro = d["project"]["name"], d["ros"]["distro"]
    root = cfg.output_root
    docker_dir = root / d["output"]["docker_dir"]
    workspace_dir = (root / d["workspace"]["host_path"]).resolve()
    container_root = d["workspace"]["container_path"]
    docker_rel = Path(os.path.relpath(docker_dir.resolve(), workspace_dir)).as_posix()
    ros_ws = posixpath.normpath(posixpath.join(container_root, d["workspace"]["ros_ws_subdir"]))
    install_dir = f"/opt/{name}"
    enabled_variants = variants.enabled(d)
    ws_rel = posixpath.relpath(ros_ws, container_root)
    ide_config = f"python3 {install_dir}/scripts/generate_ide_config.py" if d["ide"]["pyright_config"] else None
    post_create = " && ".join(c for c in (d["editor"]["post_create_command"], ide_config) if c)  # either may be empty

    return {
        **d,
        "header": f"Generated by ros2-container from {cfg.config_name}. Edit that file and re-run generate.sh instead of editing this one.",
        "docker_dir": d["output"]["docker_dir"],
        # Where Docker/ appears inside the container; None if it's outside the mounted workspace.
        "docker_dir_in_container": None if docker_rel.startswith("..") else posixpath.normpath(posixpath.join(container_root, docker_rel)),
        "service": SERVICE,
        "image": f"{name}-ros2-{distro}:dev",
        "base_image": d["ros"]["base_image"].format(distro=distro),
        "install_dir": install_dir,
        "ros_ws": ros_ws,
        "ws_prefix": "" if ws_rel == "." else f"{ws_rel}/",
        "workspace_mount": _rel(workspace_dir, docker_dir),
        "rmw_package": _ros_package(distro, d["rmw"]["implementation"]),
        "use_cyclonedds": d["rmw"]["implementation"] == "rmw_cyclonedds_cpp",
        "ros_apt_groups": {g: [_ros_package(distro, p) for p in pkgs] for g, pkgs in d["dependencies"]["ros"].items()},
        "rosdep_rules": (cfg.config_dir / d["rosdep"]["rules_file"]).read_text() if d["rosdep"]["rules_file"] else None,
        "variants": enabled_variants,
        "overlays": sorted({o for v in enabled_variants for o in v.overlays}),
        "devcontainers": _devcontainers(d, enabled_variants, root / ".devcontainer", docker_dir, post_create),
        "vscode_settings": _vscode_settings(d, ros_ws),
    }


def _devcontainers(
    d: dict, enabled_variants: list[variants.Variant], devcontainer_dir: Path, docker_dir: Path, post_create: str
) -> list[dict]:
    """One devcontainer.json per (variant, editor); cursor configs get a `-cursor` suffix."""
    if not d["editor"]["enabled"]:
        return []
    out = []
    for editor in d["editor"]["editors"]:
        extensions = d["editor"]["extensions"]["common"] + d["editor"]["extensions"][editor]
        for v in enabled_variants:
            folder = v.name if editor == "vscode" else f"{v.name}-cursor"
            config = {
                "name": f"{d['project']['display_name']} ({v.label})",
                "dockerComposeFile": [_rel(docker_dir / f, devcontainer_dir / folder) for f in v.compose_files],
                "service": SERVICE,
                "workspaceFolder": d["workspace"]["container_path"],
                **({"postCreateCommand": post_create} if post_create else {}),
                "customizations": {
                    "vscode": {
                        "extensions": extensions,
                        "settings": {
                            "terminal.integrated.defaultProfile.linux": "bash",
                            "terminal.integrated.profiles.linux": {"bash": {"path": "bash", "args": ["-l"]}},
                        },
                    }
                },
                "remoteUser": "root",
            }
            if "linux" in v.overlays:  # let the container draw on the host's X server
                config["initializeCommand"] = "command -v xhost >/dev/null && xhost +local: >/dev/null || true"
            out.append({"folder": folder, "config": config})
    return out


def _vscode_settings(d: dict, ros_ws: str) -> dict:
    # Python import paths live in pyrightconfig.json, written by generate_ide_config.py in the container.
    base = {
        "C_Cpp.default.compileCommands": f"{ros_ws}/compile_commands.json",
        "clangd.arguments": [f"--compile-commands-dir={ros_ws}"],
    }
    return deep_merge(base, d["editor"]["settings"])


def _ros_package(distro: str, name: str) -> str:
    return name if name.startswith("ros-") else f"ros-{distro}-{name.replace('_', '-')}"


def _rel(target: Path, start: Path) -> str:
    """Relative path that compose treats as a path (not a named volume)."""
    rel = Path(os.path.relpath(target, start)).as_posix()
    return rel if rel.startswith(".") else f"./{rel}"
